//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetMFTR.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adresse
    {
        public int Adresse_ID { get; set; }
        public Nullable<int> Adulte_ID { get; set; }
        public string Civic { get; set; }
        public string Rue { get; set; }
        public string Unite { get; set; }
        public string Ville { get; set; }
        public string Province { get; set; }
        public string CodePostal { get; set; }
        public string Pays { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        public virtual Adultes Adultes { get; set; }
    }
}
