//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetMFTR.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthentificationLog
    {
        public int IDAuth { get; set; }
        public System.DateTime DateAuth { get; set; }
        public string UserAttempt { get; set; }
        public string PassAttempt { get; set; }
        public string SessionID { get; set; }
    }
}
