//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetMFTR.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Parent()
        {
            this.LienReferrent = new HashSet<LienReferrent>();
            this.Transporteur = new HashSet<Transporteur>();
        }
    
        public int Parent_ID { get; set; }
        public Nullable<int> Adulte_ID { get; set; }
        public string Statut { get; set; }
        public string Sexe { get; set; }
        public Nullable<System.DateTime> Naissance { get; set; }
        public string Photo { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        public virtual Adultes Adultes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LienReferrent> LienReferrent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transporteur> Transporteur { get; set; }
    }
}
