//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetMFTR.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int IDPayments { get; set; }
        public System.DateTime DatePayment { get; set; }
        public string Carrier { get; set; }
        public string Service { get; set; }
        public int IDKid { get; set; }
        public string IDFolder { get; set; }
        public int IDParent { get; set; }
        public decimal Amount { get; set; }
        public int IDIntervenant { get; set; }
    
        public virtual Dossier Dossier { get; set; }
        public virtual Enfants Enfants { get; set; }
        public virtual Intervenant Intervenant { get; set; }
        public virtual Parent Parent { get; set; }
    }
}
