//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetMFTR.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suivi
    {
        public int suivi_id { get; set; }
        public System.DateTime dateSuivi { get; set; }
        public string moment { get; set; }
        public string remarque { get; set; }
        public int enfant_id { get; set; }
        public string dossier_id { get; set; }
        public int intervenant_id { get; set; }
    
        public virtual Dossier Dossier { get; set; }
        public virtual Enfants Enfants { get; set; }
        public virtual Intervenant Intervenant { get; set; }
    }
}
