//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetMFTR.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telephone
    {
        public int Tel_ID { get; set; }
        public Nullable<int> Adulte_ID { get; set; }
        public string Type { get; set; }
        public string Telephone1 { get; set; }
        public string Poste { get; set; }
        public string Precision { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        public virtual Adultes Adultes { get; set; }
    }
}
